package com.zhexing.sso.domain;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_id
     *
     * @mbggenerated Thu Apr 11 21:44:40 CST 2019
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.uname
     *
     * @mbggenerated Thu Apr 11 21:44:40 CST 2019
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.upassword
     *
     * @mbggenerated Thu Apr 11 21:44:40 CST 2019
     */
    private String upassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.unickname
     *
     * @mbggenerated Thu Apr 11 21:44:40 CST 2019
     */
    private String unickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.uchathead
     *
     * @mbggenerated Thu Apr 11 21:44:40 CST 2019
     */
    private String uchathead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.uphone
     *
     * @mbggenerated Thu Apr 11 21:44:40 CST 2019
     */
    private String uphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.uemail
     *
     * @mbggenerated Thu Apr 11 21:44:40 CST 2019
     */
    private String uemail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.ustatus
     *
     * @mbggenerated Thu Apr 11 21:44:40 CST 2019
     */
    private Integer ustatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.created
     *
     * @mbggenerated Thu Apr 11 21:44:40 CST 2019
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.updated
     *
     * @mbggenerated Thu Apr 11 21:44:40 CST 2019
     */
    private Date updated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_id
     *
     * @return the value of tb_user.user_id
     *
     * @mbggenerated Thu Apr 11 21:44:40 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_id
     *
     * @param userId the value for tb_user.user_id
     *
     * @mbggenerated Thu Apr 11 21:44:40 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.uname
     *
     * @return the value of tb_user.uname
     *
     * @mbggenerated Thu Apr 11 21:44:40 CST 2019
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.uname
     *
     * @param uname the value for tb_user.uname
     *
     * @mbggenerated Thu Apr 11 21:44:40 CST 2019
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.upassword
     *
     * @return the value of tb_user.upassword
     *
     * @mbggenerated Thu Apr 11 21:44:40 CST 2019
     */
    public String getUpassword() {
        return upassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.upassword
     *
     * @param upassword the value for tb_user.upassword
     *
     * @mbggenerated Thu Apr 11 21:44:40 CST 2019
     */
    public void setUpassword(String upassword) {
        this.upassword = upassword == null ? null : upassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.unickname
     *
     * @return the value of tb_user.unickname
     *
     * @mbggenerated Thu Apr 11 21:44:40 CST 2019
     */
    public String getUnickname() {
        return unickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.unickname
     *
     * @param unickname the value for tb_user.unickname
     *
     * @mbggenerated Thu Apr 11 21:44:40 CST 2019
     */
    public void setUnickname(String unickname) {
        this.unickname = unickname == null ? null : unickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.uchathead
     *
     * @return the value of tb_user.uchathead
     *
     * @mbggenerated Thu Apr 11 21:44:40 CST 2019
     */
    public String getUchathead() {
        return uchathead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.uchathead
     *
     * @param uchathead the value for tb_user.uchathead
     *
     * @mbggenerated Thu Apr 11 21:44:40 CST 2019
     */
    public void setUchathead(String uchathead) {
        this.uchathead = uchathead == null ? null : uchathead.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.uphone
     *
     * @return the value of tb_user.uphone
     *
     * @mbggenerated Thu Apr 11 21:44:40 CST 2019
     */
    public String getUphone() {
        return uphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.uphone
     *
     * @param uphone the value for tb_user.uphone
     *
     * @mbggenerated Thu Apr 11 21:44:40 CST 2019
     */
    public void setUphone(String uphone) {
        this.uphone = uphone == null ? null : uphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.uemail
     *
     * @return the value of tb_user.uemail
     *
     * @mbggenerated Thu Apr 11 21:44:40 CST 2019
     */
    public String getUemail() {
        return uemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.uemail
     *
     * @param uemail the value for tb_user.uemail
     *
     * @mbggenerated Thu Apr 11 21:44:40 CST 2019
     */
    public void setUemail(String uemail) {
        this.uemail = uemail == null ? null : uemail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.ustatus
     *
     * @return the value of tb_user.ustatus
     *
     * @mbggenerated Thu Apr 11 21:44:40 CST 2019
     */
    public Integer getUstatus() {
        return ustatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.ustatus
     *
     * @param ustatus the value for tb_user.ustatus
     *
     * @mbggenerated Thu Apr 11 21:44:40 CST 2019
     */
    public void setUstatus(Integer ustatus) {
        this.ustatus = ustatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.created
     *
     * @return the value of tb_user.created
     *
     * @mbggenerated Thu Apr 11 21:44:40 CST 2019
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.created
     *
     * @param created the value for tb_user.created
     *
     * @mbggenerated Thu Apr 11 21:44:40 CST 2019
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.updated
     *
     * @return the value of tb_user.updated
     *
     * @mbggenerated Thu Apr 11 21:44:40 CST 2019
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.updated
     *
     * @param updated the value for tb_user.updated
     *
     * @mbggenerated Thu Apr 11 21:44:40 CST 2019
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
}