
spring:
  redis:
#    host: 129.204.212.52
    port: 6379
    host: 192.168.2.123
  rabbitmq:
    host: 192.168.2.116
    port: 5672
    username: zhexing
    password:  zhexing
    publisher-confirms: true
    virtual-host: /